### ISSUE TITLE
supermarket - metadata issue

### ISSUE THREAD

**Issue by RavenB** [zuazo/postfix-dovecot-cookbook#4]
Hi,

There is a difference in the metadata between the cookbook on supermarket and the one in github (yet both are 1.2.0) 
edit : Apparently the cookbook on supermarket does not match the version here (several files are not up to date) . Would it be possible to update the supermarket cookbook with the one here in github ? That would make it much easier to knife install.

**Comment by zuazo** [comment]
The current *master* will be released as `2.0.0` soon due to [the `postfixadmin` cookbook update](https://github.com/onddo/postfixadmin-cookbook/blob/master/CHANGELOG.md#v200-2015-05-09). Give me a couple of days.

**Comment by RavenB** [comment]
Wonderful. Thank you

**Comment by zuazo** [comment]
@RavenB np :wink:

Anyway, is there any problem or bug with the old `1.2.0` version in the Supermarket? It should work.

**Comment by zuazo** [comment]
@RavenB I just released [`2.0.0`](https://github.com/zuazo/postfix-dovecot-cookbook/releases/tag/2.0.0).

**Comment by RavenB** [comment]
Downloading :) and thank you.
